GRANT CONNECT ON DATABASE vogs_dev TO "x";
GRANT USAGE ON SCHEMA public TO "x";

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO "x";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "x";

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO "x";

ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "x";

GRANT EXECUTE ON FUNCTION compute_opus_size_track() TO "x";

GRANT EXECUTE ON FUNCTION lo_manage() TO "x";

DO
$$
	DECLARE
		r RECORD;
	BEGIN
		FOR r IN SELECT oid FROM pg_largeobject_metadata
			LOOP
				EXECUTE format('ALTER LARGE OBJECT %s OWNER TO "x"', r.oid);
			END LOOP;
	END
$$;
